name: Build LiteLoader

on: [ push ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64
  ChakraCore_version: cc_windows_all_1_11_24

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Download Server
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir Tools/Server
          ServerLink=$(cat 'Scripts/LINK.txt')
          curl -L -o Tools/Server/server.zip "$ServerLink"
          unzip Tools/Server/server.zip -d Tools/Server/ > /dev/null
        shell: bash

      - name: Build Library
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd Tools
          LibraryBuilder.exe Server
        shell: cmd

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        id: build
        run: |
          MSBuild.exe ./LiteLoader.sln -property:Configuration=Release
        shell: bash

      - name: Pack Release
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd Scripts
          ./PackRelease.cmd action
        shell: cmd

      #      - name: Pack SDK
      #        working-directory: ${{env.GITHUB_WORKSPACE}}
      #        run: |
      #          cd Scripts
      #          ./PackSDK.cmd action
      #        shell: cmd

      - name: Update LiteLoaderSDK
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          git config --global user.email "LiteLDev@litebds.com"
          git config --global user.name "LiteLDev"
          cd Scripts
          ./UploadSDK.cmd action
        shell: cmd

      - name: Upload LiteLoader
        uses: actions/upload-artifact@v2
        with:
          name: LiteLoader
          path: ${{ github.workspace }}\RELEASE\

      #      - name: Upload LiteLoader SDK
      #        uses: actions/upload-artifact@v2
      #        with:
      #          name: LiteLoader-SDK
      #          path: ${{ github.workspace }}\LiteLoader-SDK.zip

      - name: Prepare for creating Release
        working-directory: ${{env.GITHUB_WORKSPACE}}
        id: rel
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          mv LiteLoader.zip LiteLoader-${GITHUB_REF#refs/*/}.zip
        shell: bash

      - name: Create New Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}\CHANGELOG.txt
          files: |
            ${{ github.workspace }}\LiteLoader-${{ steps.rel.outputs.tag }}.zip
            ${{ github.workspace }}\LiteLoader-SDK.zip
        env:
          GITHUB_REPOSITORY: LiteLDev/LiteLoaderBDS 
