name: Build LiteLoader

on: [push, pull_request, workflow_dispatch]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64
  ChakraCore_version: cc_windows_all_1_11_24

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        echo  >> src/Header/LoaderApi.h
        git log -1 --format='#define LITELOADER_VERSION_GITHUB LITELOADER_VERSION"-Ci-%h_%at"' >> headers/liteloader.h
        cat src/Header/LoaderApi.h
        MSBuild.exe ./LiteLoader.sln -property:Configuration=Release
      shell: bash
    
    - name: MkDirs
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir D:/out
        mkdir D:/out/release
        mkdir D:/out/dev
        mkdir D:/out/dev/lib
        mkdir D:/out/dev/pdb
        mkdir D:/out/dev/headers
    
    - name: Download ChakraCore
      run: |
        curl -L -o D:/cc.zip https://aka.ms/chakracore/${{ env.ChakraCore_version }}
        mkdir D:/cc
        cd D:/cc
        unzip D:/cc.zip
      shell: bash
      
    - name: Copy SymDB2 Gen
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cp -a Tool/SymDB2.exe D:/out/release
      shell: bash
    
    - name: Copy Output Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cp -a x64/Release/*.dll D:/out/release
        cp -a D:/cc/x64_release/ChakraCore.dll D:/out/release   
      shell: bash
      
    - name: Copy DevOutput Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cp -a D:/out/release/* D:/out/dev/
        cp -a x64/Release/*.lib D:/out/dev/lib
        cp -a x64/Release/*.pdb D:/out/dev/pdb
        cp -a src/Header/* D:/out/dev/headers
      shell: bash

    - name: Upload Release
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LiteLoader
        path: D:/out/release

    - name: Upload DevPack
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LiteLoader
        path: D:/out/dev
