name: Build LiteLoader

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64
  ChakraCore_version: cc_windows_all_1_11_24

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      id: build
      run: |
        MSBuild.exe ./LiteLoader.sln -property:Configuration=Release
      shell: bash
    
    - name: PackRelease & SDK
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        ./PackRelease.cmd
        ./PackSDK.cmd
      shell: cmd

    - name: Upload LiteLoader
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LiteLoader
        path: ./LiteLoader.zip
    
    - name: Upload LiteLoader-SDK
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LiteLoader
        path: | 
          ./LiteLoader.zip
          ./LiteLoader-SDK.zip

    - name: Create New Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}\CHANGELOG.txt
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: |
          ./LiteLoader.zip
          ./LiteLoader-SDK.zip
      env:
          GITHUB_REPOSITORY: LiteLDev/LiteLoaderBDS
