name: Build LiteLoader

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64
  ChakraCore_version: cc_windows_all_1_11_24

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - name: Download Lib from server
      run: |
        curl -L -o D:/plugin-lib.zip https://dl.litebds.com/build/plugin-lib.zip
        mkdir D:/lib
        unzip D:/plugin-lib.zip -d D:/lib
        rm D:/plugin-lib.zip
      shell: bash
     
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      id: build
      run: |
        echo ::set-output name=tag::${GITHUB_REF:10}
        echo  >> headers/LoaderApi.h
        git log -1 --format='#define LITELOADER_VERSION_GITHUB LITELOADER_VERSION"-Ci-%h_%at"' >> LiteLoader/Header/LoaderApi.h
        cat headers/LoaderApi.h
        MSBuild.exe ./LiteLoader.sln -property:Configuration=Release
      shell: bash
    
    - name: MkDirs
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir D:/out
        mkdir D:/out/release
        mkdir D:/out/release/plugins
        mkdir D:/out/release/plugins/lib
        mkdir D:/out/dev
        mkdir D:/out/dev/lib
        mkdir D:/out/dev/pdb
        mkdir D:/out/dev/headers
    
    - name: Download ChakraCore
      run: |
        curl -L -o D:/cc.zip https://aka.ms/chakracore/${{ env.ChakraCore_version }}
        mkdir D:/cc
        cd D:/cc
        unzip D:/cc.zip
      shell: bash
      
    - name: Copy SymDB2 Gen
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cp -a Tool/SymDB2.exe D:/out/release
      shell: bash
    
    - name: Copy Output Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cp -a Release/*.dll D:/out/release
        cp -a D:/cc/x64_release/ChakraCore.dll D:/out/release
        cp -a D:/lib/*.dll D:/out/release/plugins/lib
        cp -a x64/Release/*.lib D:/out/dev/lib
        cp -a x64/Release/*.pdb D:/out/dev/pdb
        cp -a headers/* D:/out/dev/headers
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LiteLoader
        path: D:/out/release

    - name: Upload SDK
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LiteLoader-SDK
        path: D:/out/dev

    - name: Compress to zip
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        7z a D:/out/LiteLoader-${{steps.build.outputs.tag}}.zip D:/out/release
        7z a D:/out/LiteLoader-SDK.zip D:/out/dev
      shell: bash

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}\CHANGELOG.txt
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: |
          D:/out/LiteLoader-${{steps.build.outputs.tag}}.zip
          D:/out/LiteLoader-SDK.zip
      env:
          GITHUB_REPOSITORY: LiteLDev/LiteLoaderBDS