name: CMake

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Download Server
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir Tools/Server
          ServerLink=$(cat 'Scripts/LINK.txt')
          curl -L -o Tools/Server/server.zip "$ServerLink"
          unzip Tools/Server/server.zip -d Tools/Server/ > /dev/null
          shell: bash

      - name: Build Library
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd Tools
          LibraryBuilder.exe Server
          shell: cmd

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: PackRelease
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd Scripts
          ./PackRelease.cmd action
          shell: cmd

      - name: PackSDK
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd Scripts
          ./PackSDK.cmd action
        shell: cmd

      - name: Upload LiteLoader
        uses: actions/upload-artifact@v2
        with:
          name: LiteLoader
          path: ${{ github.workspace }}\RELEASE\

      - name: Upload LiteLoader SDK
        uses: actions/upload-artifact@v2
        with:
          name: LiteLoader-SDK
          path: ${{ github.workspace }}\LiteLoader-SDK.zip