name: Auto Update LL-SDK

on: [push]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Update LL-SDK
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        git config --global user.email "LiteLDev@litebds.com"
        git config --global user.name "LiteLDev"
        UploadSDK.cmd action
      shell: cmd